--- 
- 
  connection: local
  gather_facts: false
  hosts: mx
  name: "Examples of juniper_junos_ping"
  roles: 
    - Juniper.junos
  tasks: 
    - 
      juniper_junos_ping: "host={{ inventory_hostname }} port=830 username=lab passwd=lab123 dest=192.168.0.29 count=10"
      name: "Test Ping to another devices from vmx"
      register: junos
    - debug: 
        var=junos.count
      name: junos-ping-count
    - debug:
        var=junos.dest
      name: junos-ping-destination 
