
---
-
  name: fetch the version of Junos device through xml function over ssh 
  connection: local
  hosts: mx
  gather_facts: false
  roles:
    - 
      Juniper.junos
  tasks:
    - 
      name: show version from xml_rpc 
      juniper_junos_rpc:
        rpc=get-software-information
        username='lab'
        password='lab123'
        output=text
      register: junos
    - 
      name: Print stdout_lines from xml.rpc
      debug: var=junos.stdout_lines
